### ISSUE TITLE
Crate panics on incomplete struct deserialization

### ISSUE THREAD

**Issue by kayabaNerve** [monero-rs/monero-epee-bin-serde#27]
I'd personally prefer to replace both todos with NOPs, or at least have them be an error. I will say when working with the binary RPC there's truly no value to requiring complete structs and if it's meant for people doing further work to be able to ensure their data is complete, serde provides `deny_unknown_fields` (yet not an allow_unknown_fields which allows bypassing these todos).

**Comment by thomaseizinger** [comment]
Can you provide a test or some example code that currently panics? It has been a while since I touched this!

**Comment by kayabaNerve** [comment]
I ran into it when calling `get_o_indexes.bin` with 
```
    #[derive(Deserialize, Debug)]
    struct OIndexes {
      o_indexes: Vec<u64>,
    }
```

Due to this todo, I need to expand to

```
    #[allow(dead_code)]
    #[derive(Deserialize, Debug)]
    struct OIndexes {
      o_indexes: Vec<u64>,
      status: String,
      untrusted: bool,
      credits: usize,
      top_hash: String
    }
```

While I should check status/untrusted, sure, I truly don't care about credits/top_hash and legitimately would not like to keep semi-undocumented RPC values in my code (credits is not explicitly listed under the method as it is what it is, but by keeping it, if it's ever changed, my code will break for no legitimate reason).

For JSON calls, I have the privilege of writing structs as
```
    #[derive(Deserialize, Debug)]
    struct HeightResponse {
      height: usize
    }
```
with solely relevant fields.

serde's own statement seems to be values are allowed to be ignored by structs you decode into it, unless its own tag is applied to prevent that. Therefore, in order to be in the serde spirit, at least that todo should not be present. I can't say I know what should be there either though, nor do I know for the other one.

**Comment by thomaseizinger** [comment]
Which specific todo are you hitting?

I think your request is valid but I don't have the resources at the moment to look into this :/
Definitely happy to merge a PR that fixes the issue!

**Comment by kayabaNerve** [comment]
https://github.com/monero-rs/monero-epee-bin-serde/blob/main/src/de.rs#L520 which triggers on ignored fields in the value. All good if you don't have the bandwidth.

**Comment by thomaseizinger** [comment]
Ah right. Well as a starting point, I'd probably look into other serde formats to see how they handle the situation.
