### ISSUE TITLE
deserialization of certain p2p messages fail 

### ISSUE THREAD

**Issue by Boog900** [monero-rs/monero-epee-bin-serde#36]
de-serializing a [p2p handshake](https://github.com/monero-project/monero/blob/365fd45b031b0a5c8104195dfabb786e839cb114/src/p2p/p2p_protocol_defs.h#L215) fails because when de-serializing a struct this crate [doesn't read the marker](https://github.com/monero-rs/monero-epee-bin-serde/blob/da6d6b2a058c3fd57b535966abc47ee646865605/src/de.rs#L485). 

example data to decode: 
 >01110101010102010108096e6f64655f646174610c10076d795f706f727406a04600000a6e6574776f726b5f69640a401230f171610441611731008216a1a11007706565725f6964053eb3c096c4471c340d737570706f72745f666c61677306010000000c7061796c6f61645f646174610c181563756d756c61746976655f646966666963756c7479053951f7a79aab4a031b63756d756c61746976655f646966666963756c74795f746f7036340500000000000000000e63757272656e745f68656967687405fa092a00000000000c7072756e696e675f73656564068001000006746f705f69640a806cc497b230ba57a95edb370be8d6870c94e0992937c89b1def3a4cb7726d37ad0b746f705f76657273696f6e0810

structs I used: 

```rust
#[derive(Deserialize, Debug)]
pub struct BasicNodeData {
    pub network_id: [u8; 16],
    pub my_port: u32,
    pub rpc_port: Option<u16>,
    pub rpc_credits_per_hash: Option<u32>,
    pub peer_id: u64,
    pub support_flags: u32,
}

#[derive(Deserialize, Debug)]
pub struct CoreSyncData {
    pub current_height: u64,
    pub cumulative_difficulty: u64,
    pub cumulative_difficulty_top64: u64,
    pub top_id: [u8; 32],
    pub top_version: u8,
    pub pruning_seed: u32,
}

/// A received handshake 
#[derive(Deserialize, Debug)]
pub struct HandshakeR {
    pub node_data: BasicNodeData,
    pub payload_data: CoreSyncData,
}
```

**Comment by thomaseizinger** [comment]
Happy to merge a patch that fixes it.

I am no longer using this crate myself so it is in very-low maintenance mode.
