### ISSUE TITLE
Serialization of empty sequences is incorrect

### ISSUE THREAD

**Issue by Boog900** [monero-rs/monero-epee-bin-serde#49]
If a sequence is empty the Serializer won't append a marker or it's length

example:

```rust
#[derive(Default, Deserialize, Serialize, PartialEq, Debug)]
struct TestStruct {
    seq: Vec<u32>,
}


fn test() {
    let mut obj = TestStruct::default();
    let mut data = to_bytes(&obj).unwrap();
    //assert_eq!(obj, from_bytes(&data).unwrap()); // Fails

    data.push(0x80 + 6); // Appending the marker
    data.push(0); // Appending the varint length
    assert_eq!(obj, from_bytes(&data).unwrap()); // Successful 

}
```

**Comment by Boog900** [comment]
It doesn't actually doesn't look like we are going to be able to deal with this as we wont know what marker to insert .... : (

**Comment by jeffro256** [comment]
See issue: https://github.com/monero-project/monero/pull/8940. Current epee binary deserialization code doesn't care about type markers for empty sequences

**Comment by vtnerd** [comment]
@jeffro256 the length is needed afaik ? That was the other issue @Boog900 mentioned.

**Comment by Boog900** [comment]
@vtnerd yep this is still an issue but its fixable now, I thought it wasn't fixable because we wouldn't know what marker to insert
